server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/activityplanning?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 741
  mail:
    host: smtp.qq.com
    username: dcdcddcdcdcscscd@qq.com
    password: mopjjzyxsjvejfda
    # smtp的指定端口 使用465要将protocol改为smtps
    port: 587
    properties:
      mail:
        smtp:
          ssl:
            enable=true: true
    default-encoding: UTF-8
mybatis:
  mapper-locations: classpath:mapper/*.xml
    #configuration:
  #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # mybatis打印sql语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

knife4j:
  enable: true #开启增强配置
  production: false #开启生产环境屏蔽
  basic: #开启Swagger的Basic认证功能,默认是false
    enable: true
    username: admin #Basic认证用户名
    password: 123456 #Basic认证密码
  setting:
    enableSwaggerModels: true
    swaggerModelName: 实体类列表
