server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/activityplanning?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: root
  mail:
    host: smtp.qq.com
    username: dcdcddcdcdcscscd@qq.com
    password: mopjjzyxsjvejfda
    # smtp的指定端口 使用465要将protocol改为smtps
    port: 587
    properties:
      mail:
        smtp:
          ssl:
            enable=true: true
    default-encoding: UTF-8
  # 配置文件上传大小
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
    #configuration:
  #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # mybatis打印sql语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
